# Generated by Django 4.2.5 on 2023-09-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
    ]
